# Generated by Django 5.0.2 on 2024-03-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_alter_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click link to read blog post.....', max_length=255),
        ),
    ]
