# Generated by Django 5.0.2 on 2024-04-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='instagram_url',
        ),
    ]
