# Generated by Django 5.0.2 on 2024-04-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
