# Generated by Django 5.0.2 on 2024-04-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_profile_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='proffesion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
